#!/usr/bin/env node
/**
 * Embed AI-Memory template files as Base64 into memoryTemplateStore.ts
 * Templates are extracted when user initializes AI-Memory in their workspace
 * 
 * Source: embeds/AI-Memory/*.md
 * Target: src/memoryTemplateStore.ts
 */

const fs = require('fs');
const path = require('path');

const MEMORY_DIR = path.resolve(__dirname, '../embeds/AI-Memory');
const OUTPUT_FILE = path.resolve(__dirname, '../src/memoryTemplateStore.ts');

// Memory files to embed
const MEMORY_FILES = [
  'activeContext.md',
  'decisionLog.md',
  'progress.md',
  'projectBrief.md',
  'systemPatterns.md'
];

function embedMemoryTemplates() {
  console.log('Embedding AI-Memory templates...');
  console.log(`  Source: ${MEMORY_DIR}`);
  console.log(`  Target: ${OUTPUT_FILE}`);
  console.log('');

  const templates = {};

  for (const filename of MEMORY_FILES) {
    const filePath = path.join(MEMORY_DIR, filename);
    
    if (!fs.existsSync(filePath)) {
      console.error(`  ❌ Missing: ${filename}`);
      process.exit(1);
    }

    const content = fs.readFileSync(filePath, 'utf8');
    const base64 = Buffer.from(content, 'utf8').toString('base64');
    
    // Convert filename to key (e.g., 'activeContext.md' -> 'activeContext')
    const key = filename.replace('.md', '');
    templates[key] = base64;
    
    console.log(`  ✅ Embedded: ${filename} (${content.length} chars → ${base64.length} base64)`);
  }

  // Generate TypeScript store
  const tsContent = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/embed-memory.js
// Re-run: npm run embed-memory

/**
 * AI-Memory template files embedded as Base64
 * These are extracted when user initializes AI-Memory in their workspace
 */

export type MemoryTemplateName = ${MEMORY_FILES.map(f => `'${f.replace('.md', '')}'`).join(' | ')};

const EMBEDDED_TEMPLATES: Record<MemoryTemplateName, string> = {
${Object.entries(templates).map(([key, base64]) => `  ${key}: '${base64}'`).join(',\n')}
};

/**
 * Get decoded content of a memory template
 */
export function getMemoryTemplate(name: MemoryTemplateName): string {
  const base64 = EMBEDDED_TEMPLATES[name];
  if (!base64) {
    throw new Error(\`Memory template not found: \${name}\`);
  }
  return Buffer.from(base64, 'base64').toString('utf8');
}

/**
 * Get all memory template names
 */
export function getMemoryTemplateNames(): MemoryTemplateName[] {
  return Object.keys(EMBEDDED_TEMPLATES) as MemoryTemplateName[];
}

/**
 * Get all memory templates as a map of filename -> content
 */
export function getAllMemoryTemplates(): Record<string, string> {
  const templates: Record<string, string> = {};
  for (const name of getMemoryTemplateNames()) {
    templates[\`\${name}.md\`] = getMemoryTemplate(name);
  }
  return templates;
}
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent, 'utf8');
  
  console.log('');
  console.log(`✅ Generated: ${OUTPUT_FILE}`);
  console.log(`   ${Object.keys(templates).length} templates embedded`);
}

embedMemoryTemplates();
