#!/usr/bin/env node
/**
 * Build script to embed agent files into agentStore.ts
 * 
 * Reads all *.agent.md files from the agents/ folder,
 * base64 encodes them, and regenerates agentStore.ts
 * 
 * Usage: node scripts/embed-agents.js
 * Or via npm: npm run embed-agents
 */

const fs = require('fs');
const path = require('path');

const AGENTS_DIR = path.resolve(__dirname, '../embeds/agents');
const PROTECTED_DIR = path.resolve(__dirname, '../embeds/protected');
const OUTPUT_FILE = path.resolve(__dirname, '../src/agentStore.ts');

/**
 * Derive a clean ID from filename
 * e.g., "memory-deep-think.agent.md" -> "memory-deep-think"
 */
function deriveId(filename) {
  return filename.replace(/\.agent\.md$/, '').toLowerCase();
}

/**
 * Derive a display title from file content (YAML frontmatter name: field)
 */
function deriveTitle(content, filename) {
  const nameMatch = content.match(/^name:\s*(.+)$/m);
  if (nameMatch) return nameMatch[1].trim();
  
  const headingMatch = content.match(/^#\s*(.+)$/m);
  if (headingMatch) return headingMatch[1].trim();
  
  return filename.replace(/\.agent\.md$/, '');
}

/**
 * Read all agent files and return metadata array
 */
function readAgentFiles() {
  if (!fs.existsSync(AGENTS_DIR)) {
    console.log('No agents/ directory found, skipping agents');
    return [];
  }

  const files = fs.readdirSync(AGENTS_DIR)
    .filter(f => f.endsWith('.agent.md'))
    .sort();

  console.log(`Found ${files.length} agent files:`);
  
  return files.map(filename => {
    const filepath = path.join(AGENTS_DIR, filename);
    const content = fs.readFileSync(filepath, 'utf8');
    const base64 = Buffer.from(content).toString('base64');
    
    const id = deriveId(filename);
    const title = deriveTitle(content, filename);
    
    console.log(`  - ${filename} (${id}) [${content.length} bytes -> ${base64.length} base64]`);
    
    return { id, filename, title, base64 };
  });
}

/**
 * Read all protected files and return metadata array
 */
function readProtectedFiles() {
  if (!fs.existsSync(PROTECTED_DIR)) {
    console.log('No protected/ directory found, skipping protected files');
    return [];
  }

  const files = fs.readdirSync(PROTECTED_DIR).sort();

  console.log(`Found ${files.length} protected files:`);
  
  return files.map(filename => {
    const filepath = path.join(PROTECTED_DIR, filename);
    const content = fs.readFileSync(filepath, 'utf8');
    const base64 = Buffer.from(content).toString('base64');
    
    // Derive ID from filename (handle dotfiles)
    let id = filename.replace(/\.[^.]+$/, '').toLowerCase().replace(/[^a-z0-9]+/g, '-');
    if (id.startsWith('-')) id = id.substring(1);
    if (id === '') id = filename.replace(/^\./, '').toLowerCase().replace(/[^a-z0-9]+/g, '-');
    
    // Derive title from filename or first heading
    const headingMatch = content.match(/^#\s*(.+)$/m);
    let title = headingMatch ? headingMatch[1].trim() : filename.replace(/\.[^.]+$/, '');
    if (title.startsWith('.')) title = title.substring(1);
    if (title === '') title = filename;
    
    console.log(`  - ${filename} (${id}) [${content.length} bytes -> ${base64.length} base64]`);
    
    return { id, filename, title, base64 };
  });
}

/**
 * Generate the TypeScript source code
 */
function generateTypeScript(agents, protectedFiles) {
  const agentsJson = agents.map(a => `  {
    id: '${a.id}',
    filename: '${a.filename}',
    title: '${a.title}',
    base64: '${a.base64}'
  }`).join(',\n');

  const protectedJson = protectedFiles.map(p => `  {
    id: '${p.id}',
    filename: '${p.filename}',
    title: '${p.title}',
    base64: '${p.base64}'
  }`).join(',\n');

  return `// Agent and protected-file store using Base64 embedding (mirrors promptStore.ts pattern)
// Note: vscode is imported lazily inside workspace loaders so this module can be required by Node scripts.
//
// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by: npm run embed-agents
// Source: ai-skeleton-extension/agents/*.agent.md, ai-skeleton-extension/protected/*

export interface AgentTemplate {
  id: string;
  filename: string;
  title: string;
  content: string;
}

export interface ProtectedFile {
  id: string;
  filename: string;
  title: string;
  content: string;
}

interface EmbeddedAgentMeta { id: string; filename: string; title: string; base64: string; }
interface EmbeddedFileMeta { id: string; filename: string; title: string; base64: string; }

// Embedded (baked) agent templates
const embeddedAgentsData: EmbeddedAgentMeta[] = [
${agentsJson}
];

// Embedded protected files (installed into .github/)
const embeddedProtectedFilesData: EmbeddedFileMeta[] = [
${protectedJson}
];

function decodeAgent(meta: EmbeddedAgentMeta): AgentTemplate {
  const raw = Buffer.from(meta.base64.replace(/\\n/g, ''), 'base64').toString('utf8');
  return { id: meta.id, filename: meta.filename, title: meta.title, content: raw };
}

function decodeFile(meta: EmbeddedFileMeta): ProtectedFile {
  const raw = Buffer.from(meta.base64.replace(/\\n/g, ''), 'base64').toString('utf8');
  return { id: meta.id, filename: meta.filename, title: meta.title, content: raw };
}

async function loadWorkspaceAgents(): Promise<AgentTemplate[]> {
  try {
    const vscode = await import('vscode');
    const files = await vscode.workspace.findFiles('**/.github/agents/*.agent.md', '**/node_modules/**');
    if (!files.length) return [];
    const agents: AgentTemplate[] = [];
    for (const uri of files) {
      const buf = await vscode.workspace.fs.readFile(uri);
      const text = buf.toString();
      const filename = uri.path.split('/').pop() || 'agent.md';
      const id = filename.replace(/\\.agent\\.md$/, '').toLowerCase();
      // Prefer YAML frontmatter name: or first markdown heading
      const nameMatch = text.match(/^name:\\s*(.+)$/m);
      const headingMatch = text.match(/^#\\s*(.+)$/m);
      const title = nameMatch ? nameMatch[1].trim() : (headingMatch ? headingMatch[1].trim() : filename.replace(/\\.agent\\.md$/, ''));
      agents.push({ id, filename, title, content: text });
    }
    return agents;
  } catch (e) {
    console.error('Failed to load workspace agents', e);
    return [];
  }
}

export async function getAgents(source: 'embedded' | 'workspace' | 'auto' = 'embedded'): Promise<AgentTemplate[]> {
  if (source === 'workspace') {
    const wsAgents = await loadWorkspaceAgents();
    if (wsAgents.length) return wsAgents;
  }
  if (source === 'auto') {
    const wsAgents = await loadWorkspaceAgents();
    if (wsAgents.length) return wsAgents;
  }
  return embeddedAgentsData.map(decodeAgent);
}

export function getProtectedFilesEmbedded(): ProtectedFile[] {
  return embeddedProtectedFilesData.map(decodeFile);
}
`;
}

// Main execution
console.log('\n🔧 Embedding agents into agentStore.ts...\n');

try {
  const agents = readAgentFiles();
  const protectedFiles = readProtectedFiles();
  const tsCode = generateTypeScript(agents, protectedFiles);
  
  fs.writeFileSync(OUTPUT_FILE, tsCode, 'utf8');
  
  console.log(`\n✅ Successfully generated ${OUTPUT_FILE}`);
  console.log(`   Embedded ${agents.length} agents, ${protectedFiles.length} protected files\n`);
} catch (error) {
  console.error('\n❌ Error embedding agents:', error.message);
  process.exit(1);
}
