// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/embed-memory.js
// Re-run: npm run embed-memory

/**
 * AI-Memory template files embedded as Base64
 * These are extracted when user initializes AI-Memory in their workspace
 */

export type MemoryTemplateName = 'activeContext' | 'decisionLog' | 'progress' | 'projectBrief' | 'systemPatterns';

const EMBEDDED_TEMPLATES: Record<MemoryTemplateName, string> = {
  activeContext: 'IyBBY3RpdmUgQ29udGV4dAoKIyMgQ3VycmVudCBHb2FscwoKLSBOb25lIHlldAoKIyMgQ3VycmVudCBCbG9ja2VycwoKLSBOb25lIHlldAoKLS0tCgo=',
  decisionLog: 'IyBEZWNpc2lvbiBMb2cKCnwgRGF0ZSB8IERlY2lzaW9uIHwgUmF0aW9uYWxlIHwKfC0tLS0tLXwtLS0tLS0tLS0tfC0tLS0tLS0tLS0tfAoK',
  progress: 'IyBQcm9ncmVzcwoKIyMgRG9uZQoKIyMgRG9pbmcKCgojIyBOZXh0CgotIFsgXSBVcGNvbWluZyB0YXNrCg==',
  projectBrief: 'IyBQcm9qZWN0IEJyaWVmCgojIyBPdmVydmlldwoKCiMjIEdvYWxzCgoKIyMgQ29yZSBGZWF0dXJlcwoKCiMjIFRlY2huaWNhbCBTdGFjawoKCiMjIFRhcmdldCBVc2VycwoKCiMjIFNjb3BlICYgQ29uc3RyYWludHMKCgojIyBTdWNjZXNzIENyaXRlcmlhCgo=',
  systemPatterns: 'IyBTeXN0ZW0gUGF0dGVybnMKCiMjIFRlY2huaWNhbCBTdGFjawoKIyMgQXJjaGl0ZWN0dXJhbCBQYXR0ZXJucwoKIyMgRGVzaWduIFBhdHRlcm4KCiMjIENvbW1vbiBJZGlvbXMKCi0gVGFnIGZvcm1hdDogYFtUWVBFOllZWVktTU0tRERdYCBmb3IgYWxsIG1lbW9yeSBlbnRyaWVzCi0gRGVwcmVjYXRpb246IE1hcmsgaXRlbXMgd2l0aCBgW0RFUFJFQ0FURUQ6WVlZWS1NTS1ERF1gIHJlYXNvbiAobmV2ZXIgZGVsZXRlKQotIFN1cGVyc2VkZTogTWFyayBkZWNpc2lvbnMgd2l0aCBgW1NVUEVSU0VERUQ6WVlZWS1NTS1ERF1gIG9yaWdpbmFsIOKGkiBuZXcKCg=='
};

/**
 * Get decoded content of a memory template
 */
export function getMemoryTemplate(name: MemoryTemplateName): string {
  const base64 = EMBEDDED_TEMPLATES[name];
  if (!base64) {
    throw new Error(`Memory template not found: ${name}`);
  }
  return Buffer.from(base64, 'base64').toString('utf8');
}

/**
 * Get all memory template names
 */
export function getMemoryTemplateNames(): MemoryTemplateName[] {
  return Object.keys(EMBEDDED_TEMPLATES) as MemoryTemplateName[];
}

/**
 * Get all memory templates as a map of filename -> content
 */
export function getAllMemoryTemplates(): Record<string, string> {
  const templates: Record<string, string> = {};
  for (const name of getMemoryTemplateNames()) {
    templates[`${name}.md`] = getMemoryTemplate(name);
  }
  return templates;
}
